use-grammars = { except = ["gemini"] }

[[language]]
auto-format = false
comment-tokens = ["//"]
file-types = ["rcl"]
formatter = { command = "rcl", args = ["format", "-"] }
grammar = "rcl"
indent = { tab-width = 2, unit = "  " }
name = "rcl"
roots = ["build.rcl"]
scope = "source.rcl"

[[grammar]]
name = "rcl"
source = { git = "https://github.com/rcl-lang/tree-sitter-rcl.git", rev = "master" }

[[language]]
name = "ledger"
auto-format = false
file-types = [{ glob = "finance/*.dat" }]
indent = { tab-width = 2, unit = "  " }
text-width = 64
rulers = [65]
