# Opt in to fetching and compiling Tree-sitter grammars for languages that I
# actually use. It's a long-ish list but still far less than "everything".
[use-grammars]
only = [
  "bash",
  "c",
  "cpp",
  "css",
  "csv",
  "cue",
  "diff",
  "dot",
  "elm",
  "git-commit",
  "git-config",
  "git-ignore",
  "git-rebase",
  "gn",
  "haskell",
  "hcl",
  "html",
  "idris",
  "javascript",
  "json",
  "latex",
  "ledger",
  "make",
  "markdown",
  "meson",
  "nginx",
  "nim",
  "nix",
  "pkgbuild",
  "ponylang",
  "purescript",
  "python",
  "r",
  "rcl",
  "rust",
  "sql",
  "starlark",
  "systemd",
  "text",
  "tfvars",
  "tlaplus",
  "toml",
  "typescript",
  "typst",
  "xml",
  "yaml",
  "zig",
]

[[language]]
name = "rcl"
auto-format = false
comment-tokens = ["//"]
file-types = ["rcl"]
formatter = { command = "rcl", args = ["format", "-"] }
grammar = "rcl"
indent = { tab-width = 2, unit = "  " }
roots = ["build.rcl"]
scope = "source.rcl"

[[grammar]]
name = "rcl"
source = { git = "https://github.com/rcl-lang/tree-sitter-rcl.git", rev = "master" }

[[language]]
name = "ledger"
auto-format = false
file-types = [{ glob = "finance/*.dat" }]
indent = { tab-width = 2, unit = "  " }
text-width = 64
rulers = [65]

[[language]]
name = "rust"
auto-pairs = false
auto-format = false
formatter = { command = "rustfmt", args = ["--emit", "stdout"] }
